INSERT INTO profile (pid) VALUES (1);
INSERT INTO profile (pid) VALUES (2);
INSERT INTO profile (pid) VALUES (3);
INSERT INTO profile (pid) VALUES (4);
INSERT INTO profile (pid) VALUES (5);
INSERT INTO profile (pid) VALUES (6);
INSERT INTO profile (pid) VALUES (7);
INSERT INTO social_user (profile_pid, username, email, password, role, is_online) VALUES (1, 'admin', 'joerg@joergmorbitzer.de', '$2a$12$fmhIjDL8xNOWBPi3V6ncv.Ri.ymLQlHkCzcSgBdMhrONC6MmqC1cG', 'ROLE_ADMIN', false);
INSERT INTO social_user (profile_pid, username, email, password, role, is_online) VALUES (2, 'bobo', 'bobo@bobo.tgb', '$2a$12$ShnCT88P4dqT6jtxqkAPy.pPrnKH3FCsAgtxaUA5WYYsG6x58OSIa', 'ROLE_EXP1', false);
INSERT INTO social_user (profile_pid, username, email, password, role, is_online) VALUES (3, 'didi', 'diether@mfkld.ldgk', '$2a$12$D5pJXvgSvCZmgsBqJ/zy9uVD5sYHlbXmgW49U/i/Tv1jeoz/ACnau', 'ROLE_USER', false);
INSERT INTO social_user (profile_pid, username, email, password, role, is_online) VALUES (4, 'jupp', 'jup@jup.p', '$2a$12$Rf1s0D.Wu5IG6Zrg4FLUfeYIGdBAX6kMbhOAs887lJN8UXoNX77Sq', 'ROLE_USER', false);
INSERT INTO social_user (profile_pid, username, email, password, role, is_online) VALUES (5, 'npc1', 'npc1@npc.np', '$2a$12$WvDokjnuYK1f5F1HEOnNF.YT5MHz1d4vKAykUa.VabbASb69y0do.', 'ROLE_USER', true);
INSERT INTO social_user (profile_pid, username, email, password, role, is_online) VALUES (6, 'npc2', 'npc2@npc.np', '$2a$12$t4ctig77/kqFqfXuchk19.tnD.vnPxuxdTTqWRjElpa4eJVuBRaFK', 'ROLE_EXP1', true);
INSERT INTO social_user (profile_pid, username, email, password, role, is_online) VALUES (7, 'npc3', 'npc3@npc.np', '$2a$12$2hSasFadKBORClOGTTqWH.c.qAH1vncKB8V0gWExW1s2BWNcgkfSC', 'ROLE_USER', false);
INSERT INTO social_group (name, description, founded_by_uid, is_private) VALUES ('Hilden', 'Alles über die schöne Heimat', 2, false);
INSERT INTO social_group (name, description, founded_by_uid, is_private) VALUES ('Garten', 'Arbeit im Grünen', 3, true);
INSERT INTO social_group (name, description, founded_by_uid, is_private) VALUES ('Lokalpolitik', 'Treffpunkt für Aktuelles', 2, true);
INSERT INTO memberships (social_group_gid, social_user_uid) VALUES (1, 2);
INSERT INTO memberships (social_group_gid, social_user_uid) VALUES (1, 3);
INSERT INTO memberships (social_group_gid, social_user_uid) VALUES (1, 4);
INSERT INTO memberships (social_group_gid, social_user_uid) VALUES (1, 5);
INSERT INTO memberships (social_group_gid, social_user_uid) VALUES (1, 6);
INSERT INTO memberships (social_group_gid, social_user_uid) VALUES (2, 3);
INSERT INTO memberships (social_group_gid, social_user_uid) VALUES (2, 4);
INSERT INTO memberships (social_group_gid, social_user_uid) VALUES (2, 5);
INSERT INTO memberships (social_group_gid, social_user_uid) VALUES (2, 6);
INSERT INTO memberships (social_group_gid, social_user_uid) VALUES (3, 5);
INSERT INTO memberships (social_group_gid, social_user_uid) VALUES (3, 6);
INSERT INTO memberships (social_group_gid, social_user_uid) VALUES (3, 7);
INSERT INTO pending (social_group_gid, social_user_uid) VALUES (1, 7);
INSERT INTO message (mid, fromuser_uid, touser_uid, heading, message, is_read) VALUES (0, 3, 2, 'Test', 'Test', false);
INSERT INTO message (mid, fromuser_uid, touser_uid, heading, message, is_read) VALUES (1, 2, 1, 'Huhu', 'Hallo Chef', false);
INSERT INTO message (mid, fromuser_uid, touser_uid, heading, message, is_read) VALUES (2, 1, 3, 'Willkommen', 'Herzlich Willkommen auf der Plattform', false);
INSERT INTO social_update (author_uid, title, content, target, created) VALUES (3, 'Herzlich Willkommen', 'Willkommen an alle Nutzer dieser Plattform', 0, '2023-11-30 19:23:27.419');
INSERT INTO social_update (author_uid, title, content, target, created) VALUES (2, 'Schnee', 'Damit hätte ich ja wirklich nicht gerechnet', 1, '2023-12-01 09:23:27.419');
INSERT INTO social_update (author_uid, title, content, target, created) VALUES (4, 'Was ist los', 'Et läuft alles drunner un drüber, so geht dat nich', 2, '2023-12-04 10:44:27.419');
INSERT INTO friendship (request_uid, friend_of_uid, accepted, date_of_request) VALUES ( 4, 2, false, '2023-11-30 15:28:56.500');
INSERT INTO friendship (request_uid, friend_of_uid, accepted, date_of_request) VALUES ( 2, 3, true, '2023-12-06 17:28:56.500');
INSERT INTO social_group_update (author_uid, social_group_gid, title, content) VALUES (3, 1, 'Schönes Wetter', 'Draussen scheint die Sonne ich geh kaputt. Und raus.');